[package]
name = "lexer"
version = "0.1.0"
authors = ["samtoth <sam@toth.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12"
unicode_categories = "0.1.1"

[dev-dependencies]
colored = "2.0.0"


